// This file is auto-generated by scripts/generate-api-config.js
// Do not edit manually. 
import { ApiEndpoint } from '@/types.ts';

export const API_ENDPOINTS: Record<string, ApiEndpoint> = {
  "ohlc_latest_bars": {
    "id": "ohlc_latest_bars",
    "summary": "Ohlc Latest Bars",
    "path": "/api/v2/{asset_schema}/bars/{country_symbol}/{interval}/latest",
    "method": "GET",
    "parameters": [
      {
        "name": "asset_schema",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "crypto",
          "forex",
          "stock",
          "future",
          "option"
        ],
        "title": "Asset Schema"
      },
      {
        "name": "country_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Symbol",
        "tip": "country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "interval",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "MON",
          "WEEK",
          "DAY",
          "240M",
          "120M",
          "60M",
          "30M",
          "15M",
          "10M",
          "5M",
          "3M",
          "1M"
        ],
        "title": "Interval(TimeFrame)",
        "tip": "Time interval for bars",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/interval/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "adjusted",
        "in": "query",
        "required": false,
        "type": "string",
        "default": true,
        "title": "Adjusted",
        "tip": "Whether to adjust prices for splits and dividends"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 150,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "csv",
        "options": [
          "csv",
          "json"
        ],
        "title": "Format",
        "tip": "Response format: json or csv"
      },
      {
        "name": "is_eth",
        "in": "query",
        "required": false,
        "type": "string",
        "default": false,
        "title": "Is Eth",
        "tip": "only for US stock extended trading"
      }
    ]
  },
  "ohlc_history_bars": {
    "id": "ohlc_history_bars",
    "summary": "Ohlc History Bars",
    "path": "/api/v2/{asset_schema}/bars/{country_symbol}/{interval}/from/{from_date}/to/{to_date}",
    "method": "GET",
    "parameters": [
      {
        "name": "asset_schema",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "crypto",
          "forex",
          "stock",
          "future",
          "option"
        ],
        "title": "Asset Schema"
      },
      {
        "name": "country_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Symbol",
        "tip": "country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "interval",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "MON",
          "WEEK",
          "DAY",
          "240M",
          "120M",
          "60M",
          "30M",
          "15M",
          "10M",
          "5M",
          "3M",
          "1M"
        ],
        "title": "Interval(TimeFrame)",
        "tip": "Time interval for bars",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/interval/"
      },
      {
        "name": "from_date",
        "in": "path",
        "required": true,
        "type": "date-time",
        "title": "From Date",
        "tip": "Start date for data range (ISO 8601 format)"
      },
      {
        "name": "to_date",
        "in": "path",
        "required": true,
        "type": "date-time",
        "title": "To Date",
        "tip": "End date for data range (ISO 8601 format)"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "adjusted",
        "in": "query",
        "required": false,
        "type": "string",
        "default": true,
        "title": "Adjusted",
        "tip": "Whether to adjust prices for splits and dividends"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 150,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "csv",
        "options": [
          "csv",
          "json"
        ],
        "title": "Format",
        "tip": "Response format: json or csv"
      },
      {
        "name": "next_page_key",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Next Page Key",
        "tip": "Token for pagination - get next page of results"
      },
      {
        "name": "is_eth",
        "in": "query",
        "required": false,
        "type": "string",
        "default": false,
        "title": "Is Eth",
        "tip": "only for US stock extended trading"
      }
    ]
  },
  "asset_reference": {
    "id": "asset_reference",
    "summary": "Asset Reference",
    "path": "/api/v2/{asset_schema}/reference/{country_symbol}",
    "method": "GET",
    "parameters": [
      {
        "name": "asset_schema",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "crypto",
          "forex",
          "stock",
          "future",
          "option"
        ],
        "title": "Asset Schema"
      },
      {
        "name": "country_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Symbol",
        "tip": "country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "futures_continuous_real_contracts": {
    "id": "futures_continuous_real_contracts",
    "summary": "Futures Continuous Real Contracts",
    "path": "/api/v2/future/continuous_contracts/real_contracts/{country_symbol}",
    "method": "GET",
    "parameters": [
      {
        "name": "country_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Symbol",
        "tip": "country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "futures_active_rank_real_symbol": {
    "id": "futures_active_rank_real_symbol",
    "summary": "Futures Active Rank Real Symbol",
    "path": "/api/v2/future/active_rank_contracts/real_symbol/{country_symbol}",
    "method": "GET",
    "parameters": [
      {
        "name": "country_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Symbol",
        "tip": "country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "futures_tradable_symbols": {
    "id": "futures_tradable_symbols",
    "summary": "Futures Tradable Symbols",
    "path": "/api/v2/future/contracts/tradable_symbols/{country_iso_code}",
    "method": "GET",
    "parameters": [
      {
        "name": "country_iso_code",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Iso Code",
        "tip": "Country code (e.g., US, CN, JP,GLOBAL)",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "stock_corporate_action_list": {
    "id": "stock_corporate_action_list",
    "summary": "Stock Corporate Action List",
    "path": "/api/v2/stock/stock_corporate_action/list/{country_symbol}",
    "method": "GET",
    "parameters": [
      {
        "name": "country_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Symbol",
        "tip": "country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "action_type",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Action Type",
        "tip": "'dividend' or 'split' or none"
      },
      {
        "name": "from_date",
        "in": "query",
        "required": true,
        "type": "date-time",
        "title": "From Date",
        "tip": "Start date for data range (ISO 8601 format)"
      },
      {
        "name": "to_date",
        "in": "query",
        "required": false,
        "type": "date-time",
        "title": "To Date",
        "tip": "End date for data range (ISO 8601 format)"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "json",
        "options": [
          "json",
          "csv"
        ],
        "title": "Format",
        "tip": "Response format: json or csv"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 100,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "next_page_key",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Next Page Key",
        "tip": "Token for pagination - get next page of results"
      }
    ]
  },
  "search_options": {
    "id": "search_options",
    "summary": "Search Options",
    "path": "/api/v2/option/search/{parent_full_symbol}/{option_type}/moneyness/{moneyness}",
    "method": "GET",
    "parameters": [
      {
        "name": "parent_full_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Parent Full Symbol",
        "tip": "asset_schema:country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/full_symbol/"
      },
      {
        "name": "option_type",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "call",
          "put"
        ],
        "title": "Option Type"
      },
      {
        "name": "moneyness",
        "in": "path",
        "required": true,
        "type": "enum",
        "options": [
          "in_the_money",
          "out_of_the_money"
        ],
        "title": "MoneyNess"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "min_days_to_expiration",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Min Days To Expiration"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 10,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "sort_by",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Sort By"
      },
      {
        "name": "delisted_date",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Delisted Date"
      },
      {
        "name": "strike_price",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Strike Price"
      },
      {
        "name": "ref_asset_price",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Ref Asset Price"
      },
      {
        "name": "next_page_key",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Next Page Key",
        "tip": "Token for pagination - get next page of results"
      }
    ]
  },
  "options_expiration_date_list": {
    "id": "options_expiration_date_list",
    "summary": "Options Expiration Date List",
    "path": "/api/v2/option/expiration_date_list/{parent_full_symbol}",
    "method": "GET",
    "parameters": [
      {
        "name": "parent_full_symbol",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Parent Full Symbol",
        "tip": "asset_schema:country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/full_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "economic_calendar_event_list": {
    "id": "economic_calendar_event_list",
    "summary": "Economic Calendar Event List",
    "path": "/api/v2/economic_calendar/event_list",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "country_iso_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Country Iso Code",
        "tip": "Country code (e.g., US, CN, JP,GLOBAL)",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "event_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Event Code"
      },
      {
        "name": "source_id",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Source Id"
      },
      {
        "name": "from_date",
        "in": "query",
        "required": false,
        "type": "date-time",
        "title": "From Date",
        "tip": "Start date for data range (ISO 8601 format)"
      },
      {
        "name": "to_date",
        "in": "query",
        "required": false,
        "type": "date-time",
        "title": "To Date",
        "tip": "End date for data range (ISO 8601 format)"
      },
      {
        "name": "impact",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "all",
        "options": [
          "low",
          "medium",
          "high",
          "all"
        ],
        "title": "EconomicEventImpact"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 100,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "csv",
        "options": [
          "csv",
          "json"
        ],
        "title": "Format",
        "tip": "Response format: json or csv"
      },
      {
        "name": "next_page_key",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Next Page Key",
        "tip": "Token for pagination - get next page of results"
      }
    ]
  },
  "economic_calendar_latest_event_list": {
    "id": "economic_calendar_latest_event_list",
    "summary": "Economic Calendar Latest Event List",
    "path": "/api/v2/economic_calendar/latest_event_list",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "country_iso_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Country Iso Code",
        "tip": "Country code (e.g., US, CN, JP,GLOBAL)",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "event_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Event Code"
      },
      {
        "name": "date_type",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "all",
        "options": [
          "historical",
          "upcoming",
          "all"
        ],
        "title": "EconomicEventDateType"
      },
      {
        "name": "impact",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "all",
        "options": [
          "low",
          "medium",
          "high",
          "all"
        ],
        "title": "EconomicEventImpact"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 5,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "csv",
        "options": [
          "csv",
          "json"
        ],
        "title": "Format",
        "tip": "Response format: json or csv"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      }
    ]
  },
  "economic_calendar_event": {
    "id": "economic_calendar_event",
    "summary": "Economic Calendar Event",
    "path": "/api/v2/economic_calendar/event",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "country_iso_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Country Iso Code",
        "tip": "Country code (e.g., US, CN, JP,GLOBAL)",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "event_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Event Code"
      },
      {
        "name": "source_id",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Source Id"
      },
      {
        "name": "from_date",
        "in": "query",
        "required": false,
        "type": "date-time",
        "title": "From Date",
        "tip": "Start date for data range (ISO 8601 format)"
      },
      {
        "name": "to_date",
        "in": "query",
        "required": false,
        "type": "date-time",
        "title": "To Date",
        "tip": "End date for data range (ISO 8601 format)"
      },
      {
        "name": "impact",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "all",
        "options": [
          "low",
          "medium",
          "high",
          "all"
        ],
        "title": "EconomicEventImpact"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "desc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      }
    ]
  },
  "economic_calendar_event_codes": {
    "id": "economic_calendar_event_codes",
    "summary": "Economic Calendar Event Codes",
    "path": "/api/v2/economic_calendar/event_codes/{country_iso_code}",
    "method": "GET",
    "parameters": [
      {
        "name": "country_iso_code",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Iso Code",
        "tip": "Country code (e.g., US, CN, JP,GLOBAL)",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "holiday_list": {
    "id": "holiday_list",
    "summary": "Holiday List",
    "path": "/api/v2/holiday/list",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "full_symbol",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Full Symbol",
        "tip": "asset_schema:country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/full_symbol/"
      },
      {
        "name": "holiday_code",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Holiday Code"
      },
      {
        "name": "from_date",
        "in": "query",
        "required": true,
        "type": "date-time",
        "title": "From Date",
        "tip": "Start date for data range (ISO 8601 format)"
      },
      {
        "name": "to_date",
        "in": "query",
        "required": false,
        "type": "date-time",
        "title": "To Date",
        "tip": "End date for data range (ISO 8601 format)"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 100,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "csv",
        "options": [
          "csv",
          "json"
        ],
        "title": "Format",
        "tip": "Response format: json or csv"
      },
      {
        "name": "next_page_key",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Next Page Key",
        "tip": "Token for pagination - get next page of results"
      }
    ]
  },
  "holiday_codes": {
    "id": "holiday_codes",
    "summary": "Holiday Codes",
    "path": "/api/v2/holiday/holiday_codes/{country_iso_code}",
    "method": "GET",
    "parameters": [
      {
        "name": "country_iso_code",
        "in": "path",
        "required": true,
        "type": "string",
        "title": "Country Iso Code",
        "tip": "Country code (e.g., US, CN, JP,GLOBAL)",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/country_symbol/"
      },
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "news_list": {
    "id": "news_list",
    "summary": "News List",
    "path": "/api/v2/news/list",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "full_symbol",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Full Symbol",
        "tip": "asset_schema:country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/full_symbol/"
      },
      {
        "name": "from_date",
        "in": "query",
        "required": true,
        "type": "date-time",
        "title": "From Date",
        "tip": "Start date for data range (ISO 8601 format)"
      },
      {
        "name": "to_date",
        "in": "query",
        "required": true,
        "type": "date-time",
        "title": "To Date",
        "tip": "End date for data range (ISO 8601 format)"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 100,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      },
      {
        "name": "next_page_key",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Next Page Key",
        "tip": "Token for pagination - get next page of results"
      }
    ]
  },
  "news_latest": {
    "id": "news_latest",
    "summary": "News Latest",
    "path": "/api/v2/news/latest",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      },
      {
        "name": "full_symbol",
        "in": "query",
        "required": false,
        "type": "string",
        "title": "Full Symbol",
        "tip": "asset_schema:country_iso_code:symbol",
        "help_url": "https://docs.aitrados.com/en/docs/api/terminology/full_symbol/"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "enum",
        "default": "asc",
        "options": [
          "asc",
          "desc"
        ],
        "title": "Sort",
        "tip": "Sort order: asc (ascending) or desc (descending)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 2,
        "title": "Limit",
        "tip": "Maximum number of records to return"
      }
    ]
  },
  "address_info": {
    "id": "address_info",
    "summary": "Address Info",
    "path": "/api/v2/server/address_info",
    "method": "GET",
    "parameters": [
      {
        "name": "secret_key",
        "in": "query",
        "required": true,
        "type": "string",
        "title": "Secret Key",
        "tip": "Signup to gain free secret_key",
        "help_url": "https://m.aitrados.com/secure/signup/"
      }
    ]
  },
  "read_root": {
    "id": "read_root",
    "summary": "Read Root",
    "path": "/",
    "method": "GET",
    "parameters": []
  },
  "http_check": {
    "id": "http_check",
    "summary": "Http Check",
    "path": "/http_check",
    "method": "GET",
    "parameters": []
  }
};
